#!/bin/sh
set -e

echo "*** CREATING DATABASE ***"

psql -v ON_ERROR_STOP=1 --username "$DB_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	ALTER USER $DB_USER PASSWORD '$DB_PASS';
	CREATE DATABASE $DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOSQL